version: "3.5"


services:
  db:
    image: mysql:5.7
    container_name: mysql_vicky_test
    environment:
      MYSQL_PASSWORD: 11111111
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: pockydb
    ports:
      - '8000:3306'

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_vicky_test
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: dbdox

  python:
    image: python:latest
    container_name: test2_vicky
    env_file:
      - ./ dev.env
    ports:
      - '8022:8020'
    tty: true
    volumes:
      - ./:/app:rw






